### PR TITLE
Db remodel

### PR DESCRIPTION
**Pull request by fnzr**
Tentative branch, where "tentative" is giving it too much credit.

### CODE REVIEW

**Comment by SunDwarf** [comment]
@uppfinnarn comments? I've had a quick skim over, and this seems okay, this person seems to know what they're doing (more than me currently) plus it's going in a separate branch so it's not gonna mess up master.

**Comment by HexSource** [comment]
Hey, I made a commit just now. You can login in the game. Probably. Sometimes.

To install you do migrate -> update -> user. I included the setup into the update_db, so you don't need it for now.

When you load the game, you selected your ship, it'll crash after (ship2...). Then you reload and you'll get to the main screen. Probably. This part is kinda fuzzy.

Currently, the packages being used in the game are modules, db and helpers. In the helpers package, the *Helper files aren't being used at all, just check game_start and data. The api/v1 files are a bit of a mess because I'm updating the functions only as needed. The db is where the hot stuff is going on, particularly admiral.py, so check that out.

**Comment by SunDwarf** [comment]
Screw it, merging, make sure to pull from upstream branch too as i'm gonna commit something.

**Comment by uppfinnarn** [comment]
I like what you're doing here, but what in the world are you doing with the migrations?

**Comment by SunDwarf** [comment]
That is infact one of the things I picked up on, but I didn't want to say "why the fuck are you excluding the migrations" myself.

Also the trillions of broken imports.

**Comment by HexSource** [comment]
The imports are broken because we're not going to use *Helper files, so I didn't bother correcting them, I mentioned it on the comment up there. They don't ever get called anymore even.

About migrations.. I uuuuhh don't actually know how to use them. I truncated/drop the entire database and several tables multiple times, and the migration kept complaining about version, so I just deleted everything to stop bugging me. Oops.

**Comment by SunDwarf** [comment]
Well, IMO it's better to leave them for a bit, then slowly replace them bit-by-bit with DB methods, when possible.

**Comment by HexSource** [comment]
Well, I left the broken import as means to say "If you're importing this you're doing it wrong" so I would know what I have to refactor.

I'll organize my "entry points" idea and then I'll talk a bit about it.

**Comment by HexSource** [comment]
Currently, if the url requested is api_get_member, we put it in user.py. Everything else goes on action.

So here's the idea. The game has several screens you make stuff, right? So each of these screens get an "entry point". Every request made from these screens goes to that entry point, doesn't matter if it's get_member, or req_*. So if you're working on a screen, you immediately knows where to look without going through dozens of unrelated app routes.

Also, the entry points are responsible only for calling the people who actually do stuff. So if you're equipping a girl, what the entry point does is call Kanmusu.equip() passing the relevant parameters he got from flask.request.

Similarly, the entry point is also not responsible for building the response. For this, he calls a helper with the same name (entrypoint/entry_gamestart.py calls helpers/gamestart.py) and that guy is responsible for building the api_data.

The idea is having a clear separation between db operations and response generation, while the entry point just give tasks to the right people.

Really, it sounds more complex than it is. Just take a look at the latest modules/api/entrypoint/entry_refit.py, it's pretty easy.

**Comment by SunDwarf** [comment]
Without a full error, no.

**Comment by SoftwareGuy** [comment]
If it's going to be easier for all of us, simplifying endpoints is a go in my books. Having a Shipgirl class with the appropriate functions, then a Quest class, etc and have functions in there that handle the add/remove/etc of the appropriate things is much better than having a zillion things for api endpoints. (ie. api_req_user, etc).

I'm sure you get the gist of what I'm saying. I'm looking forward to testing it when it's "stable" to some extent as I'm good at breaking things. :smile:

I'm happy to see the project come a long way from when it was just a skeleton.

**Comment by HexSource** [comment]
So...what I noticed after today is that is really hard to justify having one file for each scene. There are a lot of calls to get_member, to the point that the entire refit screen only has one route dedicated to it. 

I don't know what is the best approach, because having one file for each scene is unnecessary, but having everything in a single one irks me. I'll sleep on it I guess.

Next I'll be working on Quests, so please look forward to it.

**Pull request merged**
