### PR TITLE
Give the error page a facelift.

### PR DESCRIPTION
**Pull request by SoftwareGuy**
Originally sourced from [Danbooru](http://danbooru.donmai.us/posts/1999012). 
Photoshopped some text in, export as PNG and edit some HTML. Job done.

Adds some spice to boring error pages, no?

### CODE REVIEW

**Comment by uppfinnarn** [comment]
Not a huge fan of the font, but it works!

Just one thing: get static file URLs with: `{{ url_for('static', filename='akebono_says_it_all.png') }}`, that'll guarantee that links stay intact no mater what we change on the server.

**Comment by SunDwarf** [comment]
I vote against this because I fucking despise that kanmuau

**Comment by SoftwareGuy** [comment]
Oops... How do I remove that upstream merge commit from this pull request? Somehow it included my upstream merge...

@SunDwarf its an error message. What did you want? Nagato badly damaged instead?

**Comment by SunDwarf** [comment]
http://stackoverflow.com/a/5189600

**Comment by SoftwareGuy** [comment]
I fix this up later today and hopefully if we can merge it, I'll hold off on adding extra commits.

**Comment by SoftwareGuy** [comment]
If you can, only merge the first commit with akebono. I'm a dumb idiot and just made it worse.

I really, really, really need to relearn the git basics again.

**Comment by SunDwarf** [comment]
Feel free to open this again if you make it compatible with the main branch.

**Comment by SoftwareGuy** [comment]
Yeah, I screwed it up. I'll get my branch up to date and commit my changes in a to-merge branch and go from there.

**Pull request closed without merging**
